### PR TITLE
Code refactored with the new_helpers

### LINKED ISSUE #4: Use functions for duplicate code
Use functions for sources setup and nginx configuration setup.
This functions must be stored in an other script `functions.sh`. Then use `source functions.sh`.

### LINKED ISSUE #8: Upgrading app install as a subdomain fails
Because of issue in Nginx configuration.
Cf https://forum.duniter.org/t/alerte-inactivite-application-cesium-pour-yunohost/5115/16?u=moul.

### PR DESCRIPTION
**Pull request by rodinux**
## Problem
- *Fix #8*
- *Fix #4*
- *App is level3*

## Solution
- Change code to use the new recommended practice for the new helpers in yunohost
- Add a script change_url
- Modify the nginx.conf to resolve path traversal issues
- use the yunohost version >> 3.7.0

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/cesium_ynh%20(rodinux)/)

### CODE REVIEW

**Comment by rodinux** [comment]
keep ~ynh1 version in manifest

**Comment by rodinux** [comment]
Hi, @M5oul , I have good feedback with Jenkins to see the good practices with this code, if you can look here: https://ci-apps-dev.yunohost.org/jenkins/job/cesium_ynh%20(rodinux)/6/console
Since I just have added an 'help' key for argument 'is_public'.

**Comment by rodinux** [comment]
@M5oul, I think with this review can resolve the restore script see here: https://ci-apps-dev.yunohost.org/jenkins/job/cesium_ynh%20(rodinux)/9/console

**Comment by M5oul** [comment]
Thanks for the MR and the merge. I kind of gave up the maintenance of this package, since Cesium can be installed as a browser add-on. This package still makes sense to be deployed on a server.

**Pull request merged**
